#!/bin/bash
############################################################
## Git status watcher
############################################################

while true; do
    clear
    pwd
    git status
    sleep 1
done
