#!/bin/bash

## dotfiles
cp .vimrc ~/.vimrc
cp .bashrc ~/.bashrc
cp .tmux.conf ~/.tmux.conf
cp .SFConsole ~/.SFConsole

## vim-plug
if [ ! -f ~/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    echo "Vim-Plug installed"
fi

## fonts
if [ ! -d ~/.fonts ]; then
    curl -fLo ~/.fonts/PowerlineSymbols.otf --create-dirs https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otfs://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
    fc-cache -vf ~/.fonts/
    curl -fLo ~/.config/fontconfig/conf.d/10-powerline-symbols.conf --create-dirs https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
    echo "Powerline-patched fonts installed"
fi

echo Done!

